import NoteCreation from "../components/NoteCreation";

const Home = () => {
  return (
    <main className="page-container">
      <NoteCreation />
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin suscipit ullamcorper turpis non luctus. Suspendisse at dui dignissim, tempus tellus sit amet, venenatis dui. Ut viverra in lacus quis porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque eleifend ante, a gravida libero imperdiet vehicula. Ut lectus magna, consectetur vitae augue et, blandit vulputate lectus. Etiam nibh eros, aliquam ut accumsan sit amet, rhoncus nec est. Sed feugiat tellus dolor, et tempor nulla dictum at. Praesent condimentum faucibus quam ac pharetra. Pellentesque vestibulum libero vitae velit lacinia, a varius ex tempor. Nam pellentesque, ante id varius rhoncus, ligula urna gravida tellus, nec aliquet enim nisi ac orci. Suspendisse eget sagittis tellus. Nullam feugiat est tortor, at tristique magna dignissim at. Duis at magna ac massa venenatis porta. Sed in dolor volutpat, molestie metus luctus, feugiat nisl.

Integer non faucibus urna. Nunc ac augue in elit faucibus pellentesque. Etiam fermentum sem nec nulla interdum, et vehicula lorem elementum. Mauris vestibulum pulvinar blandit. Ut viverra rhoncus massa, a finibus velit tempus sit amet. Cras hendrerit fermentum orci vel ornare. Aenean hendrerit tempus vulputate. Phasellus magna odio, placerat ut ultrices a, mollis ut nulla. Nam tempus sapien quam, in posuere quam porttitor in. Integer mollis tortor eget nisi consequat luctus. Suspendisse sagittis, dolor vitae volutpat elementum, justo dui aliquet elit, eu porttitor leo turpis non elit. Vivamus tristique ligula ut ante imperdiet luctus. Vestibulum quis tellus ut nisl rhoncus feugiat. Morbi et luctus magna, at suscipit eros. Donec vel sem lectus. Maecenas non odio sit amet quam rutrum vestibulum a non diam.

Vivamus ac tortor vel augue aliquet varius vel et magna. In posuere ultricies condimentum. Aenean rhoncus quam ut faucibus cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus bibendum vehicula arcu, at porta nibh blandit quis. Vestibulum bibendum, turpis a ultrices malesuada, ante turpis vestibulum mi, eget sodales erat nunc ut nibh. Vivamus consectetur, felis quis pellentesque scelerisque, risus turpis maximus ex, vel faucibus mauris libero ac mi.

Sed convallis, libero sit amet vestibulum ornare, metus odio volutpat justo, in iaculis sapien tortor quis velit. Integer facilisis, felis at tempus imperdiet, diam purus volutpat risus, aliquam bibendum libero risus eu metus. In hac habitasse platea dictumst. Aenean tristique justo at felis ultrices viverra. Nam ornare dictum augue, quis congue arcu ornare eu. Sed nec tristique lorem. Aenean interdum dui ut elit venenatis lobortis. Suspendisse ornare justo felis, id cursus dui maximus eget. Donec maximus felis at augue dapibus laoreet. Mauris ut turpis ac turpis commodo aliquet. Donec vulputate condimentum libero eget posuere. Sed in imperdiet eros.

In placerat iaculis ligula at dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse quis justo nec felis pellentesque pellentesque. Ut finibus lacus lacus, ut congue erat pretium ac. In dolor magna, eleifend nec ante eget, placerat tempus neque. Sed in nulla finibus, molestie lorem ultrices, hendrerit enim. Suspendisse eget lorem ac enim condimentum tempus at maximus nunc. Sed rhoncus cursus elit mollis pellentesque. Vivamus ut porttitor justo. Duis auctor nibh augue, a fringilla purus placerat vel. Nulla facilisi. Phasellus euismod luctus urna vitae consequat. Ut ligula leo, interdum sit amet libero mattis, faucibus posuere leo. In bibendum placerat rutrum. Nullam dapibus velit magna, sed imperdiet orci posuere aliquam.

Proin nec lorem eros. Nulla augue est, consequat id massa nec, dapibus ornare sapien. Donec rutrum mi mauris, et tristique neque laoreet ac. Mauris dictum convallis ultrices. Phasellus commodo ante eget luctus lobortis. Maecenas a magna eu orci tempus semper id quis lorem. Aenean dictum placerat leo eget tempor. Suspendisse eu dolor sit amet eros fringilla maximus bibendum ac neque. Duis felis lacus, sodales non dictum feugiat, pulvinar nec ante. Phasellus lectus risus, tempus id tincidunt eget, finibus sed augue. Nam ut libero in sem fringilla commodo. Morbi ac tortor ac elit varius venenatis vel rhoncus ipsum. Fusce non neque vehicula, hendrerit tellus nec, pellentesque magna. Mauris consequat efficitur augue at commodo. Donec molestie dignissim ligula.

Integer justo neque, tristique ac velit quis, ultrices sodales mauris. Nam feugiat, dui at elementum posuere, ligula mauris pretium erat, eu luctus dolor est eget nulla. Quisque vel sapien dapibus, suscipit sapien ut, viverra elit. Etiam est augue, dapibus nec augue iaculis, luctus ultrices nulla. Nulla tempor non velit ac aliquet. Donec rutrum lectus at sodales consequat. In id mi rhoncus, mollis elit id, semper quam. Nullam lobortis aliquam libero, in venenatis tortor bibendum at. Nullam molestie mauris quis nisi ullamcorper, in volutpat orci tempus. Aenean tincidunt ante a turpis viverra malesuada. Praesent vitae nunc libero. Sed nec nibh sed ipsum semper auctor et ac mauris.

Donec dapibus et mauris quis scelerisque. Sed efficitur lectus sem, nec dictum turpis suscipit feugiat. Donec vulputate sed nunc nec finibus. Etiam in velit vel ligula luctus consequat vel mollis sapien. Cras semper luctus arcu, hendrerit tincidunt felis sodales eu. Praesent sed tristique est, in pellentesque ex. Nunc sit amet dui nec odio imperdiet faucibus. Sed nunc leo, hendrerit eu tristique non, imperdiet vel quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In mollis sapien accumsan massa semper rutrum. Donec eleifend ex lacus. Aliquam rutrum eleifend lobortis. Fusce vel justo arcu. Cras id volutpat nulla.

Ut et dui nisl. Nunc sit amet nulla mattis, gravida diam et, euismod neque. Nulla fermentum nunc pretium, pretium ante at, porta purus. Nullam ornare interdum gravida. Vestibulum a ultricies sem, eget commodo enim. Aenean justo augue, vestibulum molestie accumsan eu, molestie ac justo. Nunc elit eros, varius eu dapibus in, blandit eget odio. Suspendisse et dolor felis. Cras varius ullamcorper leo et lobortis. Donec est ipsum, dapibus at sem non, fermentum consequat magna.

Phasellus placerat scelerisque erat quis gravida. Quisque vitae accumsan orci, et auctor arcu. Nunc id ornare massa, non porta massa. Sed non urna vitae mauris gravida malesuada id non tellus. Nunc ac augue at tortor dictum dignissim vitae vehicula nibh. Morbi sed lectus ac velit facilisis bibendum. Nam gravida cursus sodales. Sed sagittis dolor ut risus rutrum, tempus semper mauris gravida. Sed id nulla at risus rhoncus sagittis sed id urna. Quisque volutpat accumsan posuere. Phasellus placerat, est vel sagittis dictum, turpis neque tempor dui, nec vehicula lacus nisi id dui. Nam in maximus ex. Morbi eu lectus dui. Mauris pretium eros vitae eros vestibulum, et tincidunt quam suscipit. Vivamus diam odio, ultrices ut cursus non, dictum sed odio. Morbi iaculis scelerisque nunc, id dapibus mi convallis sit amet.

Quisque scelerisque, arcu eu suscipit aliquet, lectus nulla hendrerit turpis, quis placerat purus massa a lorem. Nunc efficitur dui nibh, vel pharetra velit euismod consequat. Aenean nunc lorem, pellentesque eu aliquam vel, ornare maximus orci. Etiam in tincidunt dui, nec viverra velit. Nulla facilisi. Duis sollicitudin eros vel felis cursus ornare. Vivamus commodo magna vel euismod malesuada. Integer a justo at mi blandit blandit at tincidunt arcu. Sed a lorem non arcu rutrum dapibus.

Etiam lacinia arcu enim, ut laoreet ipsum sagittis id. Maecenas in neque ultrices, porttitor urna et, pharetra nunc. In hac habitasse platea dictumst. Mauris quis mauris facilisis, consequat magna malesuada, molestie lectus. Aenean feugiat consectetur justo. Fusce at nulla neque. Donec blandit, odio quis egestas pharetra, nibh ante accumsan leo, hendrerit finibus elit nunc vel quam. Quisque et turpis volutpat, sagittis augue non, hendrerit diam. Mauris lacinia mattis ullamcorper. Proin faucibus pulvinar posuere. Aliquam iaculis nibh ipsum, aliquet ultrices lorem vehicula vitae. Nunc facilisis ex sed ipsum tincidunt, quis fermentum eros consequat. Maecenas vehicula non metus nec pellentesque.

Suspendisse potenti. Quisque venenatis lorem vitae quam vestibulum, at sollicitudin leo dictum. Maecenas eget libero dapibus, euismod turpis non, luctus erat. Fusce placerat enim ut fermentum efficitur. Nulla aliquet odio eu augue lacinia pharetra. Quisque volutpat, dolor vel semper euismod, velit ipsum lacinia augue, id venenatis ante dolor eget tortor. Duis ac molestie nunc, in ultricies sem. Mauris eu finibus elit. Etiam ultricies ligula magna, eu tincidunt metus pellentesque sed. Praesent in ligula id lacus bibendum fringilla. Suspendisse congue, lacus sed consectetur egestas, massa mi bibendum tortor, imperdiet pulvinar nisi quam id diam.

Suspendisse consequat cursus mi, vel congue dui consequat sed. Nulla elementum quam sit amet leo iaculis faucibus. Vivamus tempus ultricies magna nec dignissim. Phasellus tincidunt purus sit amet nisi laoreet, eu egestas lectus semper. Aenean semper, enim id blandit vehicula, orci lacus condimentum quam, consequat convallis ligula ante sit amet libero. Quisque ut orci vitae neque eleifend pretium. Praesent eu efficitur velit. Vestibulum vitae feugiat odio, eu condimentum odio. Nulla laoreet, ex at rhoncus posuere, lacus sem luctus erat, tincidunt ultricies dolor neque eget felis. Etiam leo lectus, commodo at rutrum rutrum, ultricies at nulla. Donec ac dui quis nisl lacinia sodales eu ac purus. Sed sagittis, ipsum at dapibus eleifend, nulla orci volutpat ipsum, vel congue neque dui id dolor.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin finibus felis eu purus pretium gravida. Nulla facilisi. Vivamus diam libero, luctus quis lorem ut, tempus maximus arcu. Nam blandit ante diam, ut vestibulum ante fringilla id. Ut a gravida dui. Quisque pharetra, orci sit amet efficitur facilisis, neque ex luctus quam, sed scelerisque ante eros in purus. Fusce accumsan lectus ut vehicula rutrum. Cras pretium sed nulla id sollicitudin. Fusce non odio dictum, tincidunt mauris sed, dignissim mauris. Nullam ac justo a arcu dignissim gravida. Nulla quam nisl, dapibus sit amet mauris at, pellentesque interdum ipsum. Etiam aliquet sagittis tincidunt. Donec ultrices commodo augue, eget porta est ultricies nec. Nunc posuere metus aliquet, pulvinar magna a, suscipit sapien.

Donec lectus justo, imperdiet vel erat at, pellentesque luctus ex. Maecenas id lacus felis. Nulla nec tortor ornare, blandit lorem quis, tincidunt augue. Sed nibh leo, sagittis rutrum condimentum a, convallis eget magna. Nulla aliquet velit a tellus rhoncus imperdiet. Pellentesque fringilla tellus vitae congue molestie. Fusce nec finibus augue, id sodales mauris. Sed molestie lorem ut leo pretium, vitae rutrum ligula interdum. Sed in felis quis enim interdum gravida. Curabitur tempor est nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque dictum vel libero nec molestie. Praesent mi erat, maximus molestie luctus at, malesuada id eros. Ut scelerisque, erat id condimentum pharetra, dolor odio iaculis arcu, vitae ullamcorper eros tellus at metus.

Suspendisse rhoncus lorem in odio mollis laoreet. Sed in neque a quam lacinia sollicitudin eget nec nulla. Morbi dictum sed tellus in feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris scelerisque eget nulla non blandit. Quisque feugiat lorem non nisl molestie, non convallis arcu convallis. Nulla scelerisque molestie sodales. Vestibulum accumsan ipsum ac arcu mollis tincidunt. Mauris dapibus lacus id leo hendrerit, quis tincidunt turpis rutrum. Vestibulum vitae libero sed arcu consequat consectetur. Donec pretium, magna vitae luctus hendrerit, massa neque rhoncus dui, at luctus tortor lacus a tellus. Phasellus convallis pellentesque eros eget consequat. In hac habitasse platea dictumst. Suspendisse accumsan mi eu mollis semper. Vivamus in augue id elit pharetra sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Ut blandit sapien a sapien iaculis aliquam. Vestibulum scelerisque est at hendrerit consectetur. Fusce cursus, turpis et laoreet ultricies, dui tellus malesuada diam, ac venenatis tortor mi vel lectus. Quisque vel sem ligula. Phasellus nec fermentum est. Donec eget vehicula dui. Quisque aliquam quis ipsum ut scelerisque. Praesent tempor sed ante quis ullamcorper. Quisque nunc ex, commodo at mauris non, laoreet consectetur felis. Ut id nisi vel ex accumsan mattis. Cras sed nisi vitae arcu luctus tincidunt ac eleifend justo.

Vivamus maximus quam a elit imperdiet, dictum scelerisque ligula sagittis. Etiam urna nisl, tempor quis enim eget, egestas fermentum sem. Praesent laoreet ipsum sed diam pulvinar, ut scelerisque ante imperdiet. Maecenas varius efficitur quam a dapibus. Ut consequat ut odio quis bibendum. Integer laoreet lectus ac maximus mollis. Nulla quis ante arcu. Aliquam at metus euismod, sagittis ligula mattis, placerat turpis.

Aliquam erat volutpat. Nullam ac urna dictum, euismod leo ac, euismod odio. Nam sed mauris ac nibh bibendum volutpat. Etiam massa ex, ullamcorper et tincidunt a, ultrices vitae risus. Mauris vitae blandit dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi auctor tellus vel quam sagittis auctor. Aliquam tempus semper sem at venenatis.
    </main>
  );
};

export default Home;
